# Generated by Django 3.0.7 on 2020-06-06 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ViralUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_link', models.TextField(max_length=30)),
                ('description', models.TextField(max_length=30)),
                ('invited_users_amount', models.IntegerField()),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestTask.Image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
