# Generated by Django 3.0.7 on 2020-06-06 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TestTask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.TextField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='viraluser',
            name='description',
            field=models.TextField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='viraluser',
            name='images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='TestTask.Image'),
        ),
        migrations.AlterField(
            model_name='viraluser',
            name='invited_users_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='viraluser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
