# Generated by Django 3.0.7 on 2020-06-07 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestTask', '0005_auto_20200607_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viraluser',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='viral_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='TestTask.ViralUser'),
            preserve_default=False,
        ),
    ]
