# Generated by Django 3.0.7 on 2020-06-07 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestTask', '0006_auto_20200607_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='viral_user',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='TestTask.ViralUser'),
        ),
    ]
