# Generated by Django 3.0.7 on 2020-06-10 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestTask', '0008_auto_20200610_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viraluser',
            old_name='invite_link',
            new_name='invite_code',
        ),
    ]
